### ISSUE TITLE
Inquiry on TSEA Framework Integration and Performance Issue

### ISSUE THREAD

**Issue by EinesTages** [huanranchen/CommonWeaknessDetection#1]
I hope this message finds you well. I am reaching out regarding the integration of your code within the TSEA framework. Despite my efforts, the training outcomes have been suboptimal, with high noise in adversarial samples leading to a failed replication.

I suspect there may be a version discrepancy or an overlooked element in the integration process. Could you provide any guidance or insights that might help address these issues?

Thank you for your time and assistance.

**Comment by EinesTages** [comment]
with default TV_ETA = 2.5

**Comment by huanranchen** [comment]
@EinesTages 

I'm currently not familiar with the newest T-Sea framework, but I have the [full code](https://github.com/huanranchen/DetectionAttack) of the experiment based on the old T-Sea framework. I noticed your mention of "high noise in adversarial samples." Could you please try increasing TV_ETA? This might help.
